version: '3'

services:
  the-internet:
    image: gprestes/the-internet
    container_name: the-internet-app
    volumes:
      - ./reports:/e2e/reports
      - ./screenshots:/e2e/screenshots
    ports:
      - '7080:5000'
    environment:
      - BASE_URL
      - USER_NAME
      - PASSWORD