version: '3'

services:
  the-internet:
    image: gprestes/the-internet
    container_name: the-internet-app
    ports:
      - "7080:5000"
  automated-testing:
    image: automated-testing
    container_name: automated-testing
    build:
      dockerfile: ./Dockerfile
    ipc: host
    volumes:
      - .:/app
    environment:
      - PYTEST_BASE_URL
      - USER_NAME
      - PASSWORD